#include "AssetPath.h"

#include "Core/Application.h"

// version.h provides TASKSMACK_PROJECT_NAME_LOWER, which is set by CMake from
// ${PROJECT_NAME_LOWER} — the same variable used in the install() destination.
// This ensures the runtime search path matches the installed path without duplication.
#include "version.h"

#include <spdlog/spdlog.h>

#include <array>
#include <filesystem>
#include <functional>
#include <system_error>

namespace UI
{

namespace
{

/// Get directory containing the current executable via PathService.
[[nodiscard]] std::filesystem::path executableDir()
{
    return Core::Application::get().paths().executableDir();
}

} // namespace

std::filesystem::path selectAssetsDir(const std::filesystem::path& exeDir,
                                      const std::function<bool(const std::filesystem::path&)>& probeExists)
{
    // TASKSMACK_PROJECT_NAME_LOWER is generated by CMake from ${PROJECT_NAME_LOWER},
    // which is the same variable used in the install() destination
    // (share/<project_name_lower>/assets).
    // Use std::filesystem::path directly so operator/ accepts it without conversion.
    const std::filesystem::path appName{TASKSMACK_PROJECT_NAME_LOWER};

    // TASKSMACK_INSTALL_DATADIR is generated by CMake from ${CMAKE_INSTALL_DATADIR}
    // (defaults to "share" on Unix but may be overridden by packagers/users).
    // Using the generated constant keeps runtime search consistent with the install rule.
    const std::filesystem::path dataDir{TASKSMACK_INSTALL_DATADIR};

    // lexically_normal() resolves ".." without requiring the path to exist;
    // existence is validated below via probeExists.
    // For debug/developer workflows, prefer <exeDir>/bin/assets when present.
    const std::array<std::filesystem::path, 4> candidates = {
        exeDir / "bin" / "assets",
        exeDir / "assets",
        exeDir / dataDir / appName / "assets",
        (exeDir / ".." / dataDir / appName / "assets").lexically_normal(),
    };

    for (const auto& candidate : candidates)
    {
        if (probeExists(candidate))
        {
            spdlog::debug("Assets directory found: {}", candidate.string());
            return candidate;
        }
    }

    const std::filesystem::path fallback = exeDir / "assets";
    spdlog::warn("Assets directory not found in any expected location; defaulting to {}", fallback.string());
    return fallback;
}

std::filesystem::path findAssetsDir()
{
    // Cache the resolved directory: filesystem probing (four exists() checks) is done
    // only once per process, even when multiple layers call findAssetsDir().
    // Use the error_code overload so filesystem errors (e.g. permission denied) are
    // treated as a non-match rather than propagating as exceptions.
    static const auto result = selectAssetsDir(executableDir(),
                                               [](const std::filesystem::path& p)
                                               {
                                                   std::error_code ec;
                                                   return std::filesystem::exists(p / "fonts", ec);
                                               });
    return result;
}

} // namespace UI
