#include "AssetPath.h"

#include "Platform/Factory.h"

// version.h provides TASKSMACK_PROJECT_NAME_LOWER, which is set by CMake from
// ${PROJECT_NAME_LOWER} — the same variable used in the install() destination.
// This ensures the runtime search path matches the installed path without duplication.
#include "version.h"

#include <spdlog/spdlog.h>

#include <array>
#include <filesystem>
#include <functional>
#include <string_view>

namespace UI
{

namespace
{

/// Get directory containing the current executable via the platform path provider.
[[nodiscard]] std::filesystem::path executableDir()
{
    static const auto dir = []
    {
        auto provider = Platform::makePathProvider();
        return provider->getExecutableDir();
    }();
    return dir;
}

} // namespace

std::filesystem::path selectAssetsDir(
    const std::filesystem::path& exeDir,
    const std::function<bool(const std::filesystem::path&)>& probeExists)
{
    // TASKSMACK_PROJECT_NAME_LOWER is generated by CMake from ${PROJECT_NAME_LOWER},
    // which is the same variable used in the install() destination
    // (share/<project_name_lower>/assets).
    const std::string_view APP_NAME = TASKSMACK_PROJECT_NAME_LOWER;

    // lexically_normal() resolves ".." without requiring the path to exist;
    // existence is validated below via probeExists.
    const std::array<std::filesystem::path, 3> candidates = {
        exeDir / "assets",
        exeDir / "share" / APP_NAME / "assets",
        (exeDir / ".." / "share" / APP_NAME / "assets").lexically_normal(),
    };

    for (const auto& candidate : candidates)
    {
        if (probeExists(candidate))
        {
            spdlog::debug("Assets directory found: {}", candidate.string());
            return candidate;
        }
    }

    spdlog::warn("Assets directory not found in any expected location; defaulting to {}", candidates[0].string());
    return candidates[0];
}

std::filesystem::path findAssetsDir()
{
    // Cache the resolved directory: filesystem probing (three exists() checks) is done
    // only once per process, even when multiple layers call findAssetsDir().
    static const auto result = selectAssetsDir(
        executableDir(),
        [](const std::filesystem::path& p) { return std::filesystem::exists(p / "fonts"); });
    return result;
}

} // namespace UI
