name: Build Windows Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-windows-release-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-windows-release:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      os: windows-2025
      build_type: release
      llvm-semver-version: '22.1.0'
