name: Build Linux Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-linux-release-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-linux-release:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      os: ubuntu-24.04
      build_type: release
      llvm-version: '22'
